# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


Import('server_sample_env')

if not server_sample_env.has_key('_ALLJOYNCORE_'):
    server_sample_env.Append(LIBS = ['alljoyn'])
    if server_sample_env['BR'] == 'on' :
        brFile = server_sample_env.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        server_sample_env['brobj'] = File(brFile)
        server_sample_env['ajrlib'] = 'ajrouter'
    if server_sample_env['OS'] == 'openwrt':
        server_sample_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

# Make serversample dist a sub-directory of the alljoyn dist.  This avoids any conflicts with alljoyn dist targets.
server_sample_env['SAMPLE_APPS_DISTDIR'] = server_sample_env['DISTDIR'] + '/sample_apps'

# Sample programs
if server_sample_env['BUILD_SERVICES_SAMPLES'] == 'on':
    server_sample_env.Install('$SAMPLE_APPS_DISTDIR/bin', server_sample_env.SConscript('samples/SConscript', exports = ['server_sample_env']))

# Build docs
installDocs = server_sample_env.SConscript('docs/SConscript', exports = ['server_sample_env'])
server_sample_env.Depends(installDocs, server_sample_env.Glob('$ONBOARDING_DISTDIR/inc/alljoyn/onboarding/*.h'));
