#******************************************************************************
# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#*****************************************************************************

Import('cpsenv')

srcs = cpsenv.Glob('*.cc')
srcs += cpsenv.Glob('Widgets/*.cc')
srcs += cpsenv.Glob('BusObjects/*.cc')

libs = []

# Static library
objs = cpsenv.Object(srcs)
libs.append(cpsenv.StaticLibrary('alljoyn_controlpanel', objs))

# Shared library
if cpsenv.get('LIBTYPE', 'static') != 'static':
    shobjs = cpsenv.SharedObject(srcs)
    libs.append(cpsenv.SharedLibrary('alljoyn_controlpanel', shobjs))

Return('libs')
