# Copyright (c) 2013 - 2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('nsenv')
 
if not nsenv.has_key('_ALLJOYNCORE_'):
    nsenv.Append(LIBS = ['alljoyn'])
    if nsenv['BR'] == 'on' :
        brFile = nsenv.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        nsenv['brobj'] = File(brFile)
        nsenv['ajrlib'] = 'ajrouter'
    if nsenv['OS'] == 'openwrt':
        nsenv.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

nsenv['NS_DISTDIR'] = nsenv['DISTDIR'] + '/notification'

nsenv.Install('$NS_DISTDIR/inc/alljoyn/notification', nsenv.Glob('inc/alljoyn/notification/*.h'))
nsenv.Install('$NS_DISTDIR/lib', nsenv.SConscript('src/SConscript', exports = ['nsenv']))
if nsenv['BUILD_SERVICES_SAMPLES'] == 'on':
    nsenv.Install('$NS_DISTDIR/bin', nsenv.SConscript('samples/SConscript', exports = ['nsenv']))

# Build docs
installDocs = nsenv.SConscript('docs/SConscript', exports = ['nsenv'])
nsenv.Depends(installDocs, nsenv.Glob('$NS_DISTDIR/inc/alljoyn/notification/*.h'));
