# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Import('tsenv')
 
if not tsenv.has_key('_ALLJOYNCORE_'):
    tsenv.Append(LIBS = ['alljoyn'])
    if tsenv['BR'] == 'on' :
        brFile = tsenv.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        tsenv['brobj'] = File(brFile)
        tsenv['ajrlib'] = 'ajrouter'
    if tsenv['OS'] == 'openwrt':
        tsenv.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

tsenv['TS_DISTDIR'] = tsenv['DISTDIR'] + '/time'

tsenv.Install('$TS_DISTDIR/inc/alljoyn/time', tsenv.Glob('inc/alljoyn/time/*.h'))
tsenv.Install('$TS_DISTDIR/lib', tsenv.SConscript('src/SConscript', exports = ['tsenv']))
if tsenv['BUILD_SERVICES_SAMPLES'] == 'on':
    tsenv.Install('$TS_DISTDIR/bin', tsenv.SConscript('samples/SConscript', exports = ['tsenv']))

# Build docs
installDocs = tsenv.SConscript('docs/SConscript', exports = ['tsenv'])
tsenv.Depends(installDocs, tsenv.Glob('$TS_DISTDIR/inc/alljoyn/time/*.h'));
